//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Vuelos
    {
        public int Id { get; set; }
        public string Nombre_Vuelo { get; set; }
        public string Origen_Vuelo { get; set; }
        public string Destino_Vuelo { get; set; }
        public string Salida_Tiempo { get; set; }
        public string Llegada_Tiempo { get; set; }
        public string Clase_Vuelo { get; set; }
        public Nullable<decimal> Cargos_Vuelo { get; set; }
        public Nullable<int> Asientos { get; set; }
    }
}
