//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_final
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AerolineaDBEntities1 : DbContext
    {
        public AerolineaDBEntities1()
            : base("name=AerolineaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Detalle_Clientes> Detalle_Clientes { get; set; }
        public virtual DbSet<Detalle_Vuelos> Detalle_Vuelos { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
    }
}
