//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public Nullable<int> Cliente_ID { get; set; }
        public Nullable<System.DateTime> Cliente_FECHADEVIEAJE { get; set; }
        public Nullable<int> CLIENTE_IDVUELO { get; set; }
        public Nullable<int> CLLIENTE_ASIENTO_ { get; set; }
    }
}
